### PR TITLE
add tensorflow

### PR DESCRIPTION
**Pull request by flip111**

### CODE REVIEW

**Comment by adamgreig** [comment]
Just to note I think we should resolve the various discussions about the template and format of new items in #6 before merging in this PR.

**Comment by flip111** [comment]
@adamgreig i think that is an excellent idea. How can we get the discussion of this template going?

**Comment by jacobrosenthal** [comment]
https://github.com/Recognition2/tfmicro

**Comment by flip111** [comment]
Closing because embedded programming has lost my interest.

**Pull request closed without merging**
